version: '3.7'

volumes:
  db_data:
      driver: local

services:
  db:
      image: postgres:12-alpine
      volumes:
        - db_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  auth:
      build: .
      environment:
        DB_VENDOR: postgres
        DB_ADDR: db
        DB_DATABASE: ${POSTGRES_DB}
        DB_USER: ${POSTGRES_USER}
        DB_PASSWORD: ${POSTGRES_PASSWORD}
        KEYCLOAK_USER: ${KEYCLOAK_USER}
        KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      ports:
        - 8080:8080
      depends_on:
        - db